"""Episodic store memory — distilled profiles from prior RCA outcomes.

Profiles are stored in Supabase public.rca_city_profile.
Each profile is a compact markdown summary generated by the LLM from N prior outcomes.

Commands:
    rca distil [--store ALIAS]   — generate/update profiles
    rca reset-memory [--store ALIAS | --all]  — delete profiles
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Callable

ClientFactory = Callable[[str], Any]

DISTIL_SYSTEM_PROMPT = """You are writing an episodic memory profile for an individual retail store.

Based on the RCA history provided, write a compact 3-5 bullet summary of known patterns.

Rules:
- State what the evidence shows, not what you infer beyond it
- Quantify using normalized sales amounts or percentages, never currency
- If only 1-2 episodes exist, say so plainly and keep confidence low
- Store aliases and city IDs are opaque identifiers — do not label them
- Write in markdown list format (each bullet starts with "- ")
- Start directly with the bullets, no preamble

Example output:
- Sales drops have triggered 3 prior RCAs; stockout pressure was the most cited driver (2/3 runs).
- Confidence was low in all prior runs, suggesting complex or overlapping drivers.
- Weekday pattern shows Monday dips relative to fleet average (per normals below).
- One prior escalation (2024-05-01): confirmed stockout during a promotional period.
"""


def _make_client(settings: Any) -> Any:
    from rca.llm import build_openai_compatible_client
    return build_openai_compatible_client(settings)


def get_store_profile(city_id: int) -> str | None:
    """Return stored profile markdown for a store, or None if not found."""
    if not os.getenv("SUPABASE_URL"):
        return None
    try:
        from rca.config import make_supabase_client
        client = make_supabase_client()
        result = (
            client
            .table("rca_city_profile")
            .select("profile_markdown")
            .eq("store_id", city_id)
            .limit(1)
            .execute()
        )
        rows = result.data or []
        if rows and rows[0].get("profile_markdown"):
            return str(rows[0]["profile_markdown"])
        return None
    except Exception:
        return None


def reset_store_profile(city_id: int | None = None) -> int:
    """Delete profile(s) from Supabase. Returns count deleted.

    city_id=None deletes all profiles.
    """
    if not os.getenv("SUPABASE_URL"):
        raise RuntimeError("SUPABASE_URL not set — cannot reset profiles.")

    from rca.config import make_supabase_client
    client = make_supabase_client()
    if city_id is not None:
        result = client.table("rca_city_profile").delete().eq("store_id", city_id).execute()
    else:
        # Delete all — match everything with a truthy condition
        result = client.table("rca_city_profile").delete().neq("store_id", "").execute()
    return len(result.data or [])


def distil_store_profile(
    city_id: int,
    settings: Any,
    client_factory: ClientFactory | None = None,
    dry_run: bool = False,
    outcome_limit: int = 10,
) -> str:
    """Generate a profile for one store and upsert it to Supabase.

    Returns the generated profile markdown.
    dry_run=True generates the profile but does not write to Supabase.
    """
    from rca.llm import build_chat_completion_kwargs, build_openai_compatible_client
    from rca.outcomes import get_prior_rca

    # Fetch prior outcomes
    prior = get_prior_rca(city_id, limit=outcome_limit)
    episode_count = prior.get("previous_trigger_count", 0)

    # Fetch normals from Supabase if available
    normals: dict[str, Any] = {}
    if os.getenv("SUPABASE_URL") and not dry_run:
        try:
            from rca.config import make_supabase_client
            sb = make_supabase_client()
            result = (
                sb.table("rca_city_normals")
                .select("avg_sale,stddev_sale,p25_sale,p50_sale,p75_sale,dow_pattern")
                .eq("store_id", city_id)
                .limit(1)
                .execute()
            )
            rows = result.data or []
            if rows:
                normals = dict(rows[0])
        except Exception:
            pass

    user_content = (
        f"Store: {city_id}\n"
        f"Episodes in RCA history: {episode_count}\n\n"
        f"Prior outcomes (most recent first):\n"
        f"{json.dumps(prior.get('recent_outcomes', []), indent=2)}\n\n"
        f"Top driver counts:\n"
        f"{json.dumps(prior.get('top_driver_counts', []), indent=2)}\n\n"
    )
    if normals:
        user_content += (
            f"Store baseline normals (normalized sales amounts, not currency):\n"
            f"{json.dumps(normals, indent=2)}\n"
        )

    messages = [
        {"role": "system", "content": DISTIL_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

    factory = client_factory or (lambda _: build_openai_compatible_client(settings))
    client = factory("story_writer")  # story_writer → fast model tier
    response = client.chat.completions.create(
        **build_chat_completion_kwargs(settings, messages, tools=None)
    )
    profile_markdown = (response.choices[0].message.content or "").strip()

    if not dry_run and os.getenv("SUPABASE_URL"):
        from rca.config import make_supabase_client
        sb = make_supabase_client()
        sb.table("rca_city_profile").upsert(
            {
                "store_id": city_id,
                "profile_markdown": profile_markdown,
                "episode_count": episode_count,
                "distilled_at": datetime.now(timezone.utc).isoformat(),
            },
            on_conflict="store_id",
        ).execute()

    return profile_markdown


def distil_all_stores(
    settings: Any,
    client_factory: ClientFactory | None = None,
    dry_run: bool = False,
) -> list[tuple[str, str]]:
    """Distil profiles for every store that has at least one prior outcome.

    Returns list of (city_id, profile_markdown).
    """
    if not os.getenv("SUPABASE_URL"):
        raise RuntimeError("SUPABASE_URL not set — cannot distil profiles.")

    from rca.config import make_supabase_client
    sb = make_supabase_client()
    result = (
        sb.table("rca_outcome")
        .select("store_id")
        .execute()
    )
    rows = result.data or []
    city_ides = sorted({str(r["store_id"]) for r in rows})

    results: list[tuple[str, str]] = []
    for alias in city_ides:
        profile = distil_store_profile(
            alias, settings=settings, client_factory=client_factory, dry_run=dry_run
        )
        results.append((alias, profile))
    return results
